version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build:
    commands:
      - echo [Pre-Build] Logging in to Amazon ECR.
      - aws --version
      - eval $(aws ecr get-login --region us-east-2 --no-include-email | sed 's|https://||')
      - REPOSITORY_URI=685293513802.dkr.ecr.us-east-2.amazonaws.com/rpg-companion/core-image
      - IMAGE_TAG=1.0
  build:
    commands:
      - echo [Build] Build started on `date`.
      - echo [Build] Install dependencies.
      - composer install
      - echo [Build] Creating env file
      - cp .env.production .env
      - php artisan key:generate
      - echo [Build] Building docker image
      - docker build -t $REPOSITORY_URI:latest -f docker/production/Dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo [Post-Build] Build completed on `date`
      - docker image ls -a
      - echo [Post-Build] Pushing image to repository
      - docker push $REPOSITORY_URI:$IMAGE_TAG
